#!/usr/bin/env bash
# Project: Processes and signals
# displays a list of currently running processes:
#   show all processes, for all users, including those 
#   which might not have a TTY and process hierarchy in
#   a user-oriented format.
ps -auxf
