#!/usr/bin/env bash
# displays "To infinity and beyond" indefinitely
# or "I am invincible!!!" when receiving a SIGTERM signal
# Project: Processes and signals
trap "echo I am invincible!!!" SIGTERM
while true; do
    echo "To infinity and beyond"
    sleep 2
done
