#!/usr/bin/env bash
# displays numbers from 1 to 100.
# FizzBuzz when the number is a multiple of 3 and 5
# Fizz when the number is multiple of 3
# Buzz when the number is a multiple of 5
i=1
while [ $i -lt 101 ]
do
    text=""
    if (( i % 5 == 0 )); then
        text="${text}Fizz"
    fi
    if (( i % 3 == 0 )); then
        text="${text}Buzz"
    fi
    if [ "$text" = "" ]; then
        echo "$i"
    else
        echo "$text"
    fi
    i=$((i+1))
done